[package]
name = "cid"
version = "0.5.1"
description = "CID in rust"
homepage = "https://github.com/multiformats/rust-cid"
authors = ["Friedel Ziegelmayer <dignifiedquire@gmail.com>"]
keywords = ["ipld", "ipfs", "cid", "multihash", "multiformats"]
license = "MIT"
readme = "README.md"
edition = "2018"

[lib]
name = "cid"

[features]
default = ["std"]
std = []
test = ["quickcheck", "rand"]

[package.metadata.release]
pre-release-commit-message = "Release {{version}} 🎉🎉"
no-dev-version = true

[dependencies]
multibase = "0.8.0"
multihash = { version = "0.2.0", default-features = false }
unsigned-varint = "0.4.0"

quickcheck = { version = "0.9.2", optional = true }
rand = { version = "0.7.3", optional = true }

[dev-dependencies]
multihash = { version = "0.2.0", features = ["test"] }
quickcheck = "0.9.2"
rand = "0.7.3"

[patch.crates-io]
multihash = { path = "../tiny-multihash" }
